{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "device-metrics.namespace" . }}
  labels:
    {{- include "device-metrics.labels" . | nindent 4 }}
{{- end }}

