apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-metrics.fullname" . }}-frontend
  namespace: {{ include "device-metrics.namespace" . }}
  labels:
    {{- include "device-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.frontend.name }}
  selector:
    {{- include "device-metrics.selectorLabels" . | nindent 4 }}
    component: frontend

